### ISSUE TITLE
Website not up to date

### ISSUE THREAD

**Issue by atsju** [weedo3d/TINA2firmware#1]
On your website the is only up to 2.11 version available. 
You should update website to reflect the 2.16 release 

http://www.weedo3dprinter.com/doku.php/firmware/tina2

**Comment by weedo3d** [comment]
We have published the 2.16.0 firmware on the wiki site and the product site.

**Comment by Sinclair-ZX81** [comment]
@weedo3d
There are a number of websites out there for TINA2 (and other WEEDO printer).
Just for instance my collection of (outdated) firmware related pages:

Source 1 (most up-to-date): [http://www.weedo3dprinter.com/doku.php/firmware/tina2](http://www.weedo3dprinter.com/doku.php/firmware/tina2)
Source 2 (outdated): [http://www.weedotina2.com/doku.php?id=firmware:tina2](http://www.weedotina2.com/doku.php?id=firmware:tina2)
Source 3 (most outdated): [http://www.weedo.ltd/wiki/doku.php?id=firmware:tina2](http://www.weedo.ltd/wiki/doku.php?id=firmware:tina2)

Maybe I miss one ... :)

I'm not sure if you are responsible for all of them; if so, please think about making just only one source webside. Would make it easier to find latest builds of wiibuilder and firmware, for instance.
