### ISSUE TITLE
M50X not responding

### ISSUE THREAD

**Issue by ghost** [weedo3d/TINA2firmware#6]
I tried to calibrate the e-steps but the M503 Command gave no response, no matter wether sent via pronterface, cura or wiibuilder. Why is this?

**Comment by Sinclair-ZX81** [comment]
If you have a micro SD card in the slot, please remove it and try it again.
With inserted SD most times I get no echo from my printer on several commands like M115, M503, ... (pronterface).

**Comment by ghost** [comment]
Unbelievable.... thank you for that - it works now.
